DROP TABLE IF EXISTS sq06_clues;
DROP TABLE IF EXISTS sq06_verification;

CREATE TABLE "sq06_clues" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "quest_pk" TEXT UNIQUE,
  "quest_sk" TEXT,
  "muxes" TEXT,
  "timestamp" DATETIME DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE "sq06_verification" (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "quest_pk" TEXT,
  "success" INTEGER,
  "timestamp" DATETIME DEFAULT CURRENT_TIMESTAMP
)
;
